/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_test_TestJNI */

#ifndef _Included_com_example_jniTest_MainActivity
#define _Included_com_example_jniTest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_test_TestJNI
 * Method:    getMac
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jniTest_MainActivity_getMac
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
